version: "2.1"

services:
  jobmanager:
    container_name: ${JOBMANAGER_NAME}
    image: flink:1.9.0
    volumes:
      - ${HOST_PATH}:${CONT_PATH}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    container_name: ${TASKMANAGER_NAME}
    image: flink:1.9.0
    volumes:
      - ${HOST_PATH}:${CONT_PATH}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

